### ISSUE TITLE
Using interrupts on digital pins

### ISSUE THREAD

**Issue by szerwi** [TD-er/SC16IS752#1]
Hi,
Can someone explain me how to use interrupts in this expander? I would like to detect changes on digital pins. Does the expander store pin number by which the interrupt was trigerred or do I need to read all the pins and define which pin trigerred the interrupt by myself in Arduino code?

**Comment by TD-er** [comment]
To be honest, I have not looked into that feature so I don't even know if the chip supports it.
Sounds like a useful feature though.

For ESPEasy (for which I adapted the library) I do not yet use the GPIO pins of this I2C to UART bridge.
Later when I do, I will also look into this interrupt suggestion you made, but I don't expect this to be implemented in the next few months to be honest.

**Comment by szerwi** [comment]
@TD-er Thank you for the information. I am still waiting for the expander to arrive. I will look into interrupts when it arrives to me. I will share the results here if I come to any :)

**Comment by szerwi** [comment]
@TD-er I have just received the expander, but I can't get it working. Do you know if the library is compatible with ESP32?
The device is found on address 0x4D. I haven't found this address in library's define section, so I've put the address manually.
 Unfortunately, the ping function from the library returns 0
This is my whole code:
```
#include <Wire.h>
#include <SC16IS752.h>

#define GPIO 0

SC16IS752 i2cuart = SC16IS752(SC16IS750_PROTOCOL_I2C, 0X4D);

void setup() 
{
    Serial.begin(9600);
    Serial.println("Start testing");
    Wire.begin(4, 16);
    // UART to Serial Bridge Initialization
    i2cuart.begin(SC16IS752_DEFAULT_SPEED, SC16IS752_DEFAULT_SPEED); //baudrate setting
    if (i2cuart.ping()!=1) {
        Serial.println("Device not found");
        while(1);
    } else {
        Serial.println("Device found");
    }

    i2cuart.pinMode(GPIO, INPUT);
}

void loop() 
{
    Serial.println(i2cuart.digitalRead(GPIO));
    delay(2000);
}
```

Here is the output after powering up:
```
ReadRegister channel=0 reg_addr=18 result=FF
WriteRegister channel=0 reg_addr=18 val=FF
WriteRegister channel=0 reg_addr=0 val=3
WriteRegister channel=0 reg_addr=8 val=0
WriteRegister channel=0 reg_addr=18 val=7F
Desired baudrate: 9600
Calculated divisor: 3
Actual baudrate: 9600
Baudrate error: 0
ReadRegister channel=1 reg_addr=22 result=FF
ReadRegister channel=1 reg_addr=1A result=FF
WriteRegister channel=1 reg_addr=1A val=FF
WriteRegister channel=1 reg_addr=2 val=3
WriteRegister channel=1 reg_addr=A val=0
WriteRegister channel=1 reg_addr=1A val=7F
Desired baudrate: 9600
Calculated divisor: 3
Actual baudrate: 9600
Baudrate error: 0
ReadRegister channel=0 reg_addr=18 result=FF
LCR Register:0x192
WriteRegister channel=0 reg_addr=18 val=C3
ReadRegister channel=1 reg_addr=1A result=FF
LCR Register:0x192
WriteRegister channel=1 reg_addr=1A val=C3
WriteRegister channel=0 reg_addr=38 val=55
ReadRegister channel=0 reg_addr=38 result=FF
Device not found

```

EDIT: Problem solved. I wanted to use different I2C pins, so I've replaced all "WIRE" words with "Wire" in the library, so I can use I2C on different pins.

**Comment by TD-er** [comment]
It does work just fine on ESP32
What you should keep in mind is that the NXP datasheet does mention the I2C addresses in 7 bit notation, thus including the read/write bit.
The found addresses via an I2C scan is thus the NXP datasheet addresses / 2.

**Comment by szerwi** [comment]
@TD-er Can you help me with using interrupts on digital pins? Here is my code:
```
#include <Wire.h>
#include <SC16IS752.h>

#define GPIO 1
#define IRQ 25

unsigned long readTime;

SC16IS752 i2cuart = SC16IS752(SC16IS750_PROTOCOL_I2C, 0x4D);

void irq() {
  Serial.println("Interrupt");
}

void setup() 
{
  Serial.begin(9600);
  Serial.println("Start testing");
  Wire.begin(4, 16);
  
  // UART to Serial Bridge Initialization
  i2cuart.begin(SC16IS752_DEFAULT_SPEED, SC16IS752_DEFAULT_SPEED); //baudrate setting
  if (i2cuart.ping()!=1) {
      Serial.println("Device not found");
      while(1);
  } else {
      Serial.println("Device found");
  }
  pinMode(IRQ, INPUT_PULLUP);
  i2cuart.pinMode(GPIO, INPUT);
  i2cuart.InterruptControl(SC16IS752_CHANNEL_BOTH, 3);
  i2cuart.SetPinInterrupt(GPIO);
  attachInterrupt(digitalPinToInterrupt(IRQ), irq, FALLING);
}

void loop() 
{
  if(millis() - readTime > 2000) {
    i2cuart.GPIOGetPortState();
    Serial.print("IRQ: "); Serial.println(digitalRead(IRQ));
    Serial.print("GPIO: "); Serial.println(i2cuart.digitalRead(GPIO));
    Serial.print("InterruptPendingTest: "); Serial.println(i2cuart.InterruptPendingTest(SC16IS752_CHANNEL_BOTH));
    Serial.println("");
    readTime = millis();
  }
}
```

Here is the output after powering up:
```
IRQ: 0
GPIO: 0
InterruptPendingTest: 0

IRQ: 1
GPIO: 0
InterruptPendingTest: 1
```
First reading on IRQ is 0, like it detected the interrupt, but next readings on IRQ and InterruptPendingTest are always 1, no matter the GPIO state.

**Comment by TD-er** [comment]
I have not read the datasheet on it, but I can imagine you may need to reset the pending interrupt.
Or it may trigger a lot, so maybe force it to a state by pulling it hard to 0 or 1 and for sure don't leave it floating.

**Comment by szerwi** [comment]
If I understand the documentation correctly, I reset the interrupt by calling ```InterruptPendingTest()```
IRQ pin is internally pulled up. The IRQ is triggered when it is in LOW state, so in my situation the IRQ is never trigerred.

**Comment by szerwi** [comment]
I've managed to get interrupts working. I had to modify the library so it can properly handle writing and reading from IoIntEna register. I can submit a PR if you want ;)
I've also reimplemented readBytes function (it is commented out in your library) and I will try to add readBytesUntil function.

**Comment by TD-er** [comment]
> I can submit a PR if you want ;)

Yes please :)

**Comment by TD-er** [comment]
This is now (finally) merged...
